name: Build

on:
  push:
    paths:
      - "config/*.txt"
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"

jobs:
  check:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          mkdir build && mkdir tmp && cp bootstrap.bat build/bootstrap.bat
          export py_version=$(cat config/Python.txt)
          curl -fSL "https://www.python.org/ftp/python/${py_version}/python-${py_version}-embed-amd64.zip" -o tmp/python-${py_version}-embed.zip
          unzip tmp/python-${py_version}-embed.zip -d build/Python3
          sed -i "s|#import site|import site|g" $(ls build/Python3/*._pth)

      - name: Install pip&cython
        run: |
          export PATH=$(pwd)/build/Python3:$(pwd)/build/Python3/Scripts:${PATH}
          curl -fSL "https://bootstrap.pypa.io/get-pip.py" -o tmp/get-pip.py
          python tmp/get-pip.py
          pip install cython

      - name: Install VapourSynth
        run: |
          export vs_version=$(cat config/VapourSynth.txt)
          curl -fSL "https://github.com/vapoursynth/vapoursynth/releases/download/${vs_version}/VapourSynth64-Portable-${vs_version}.7z" -o tmp/VapourSynth64-Portable-${vs_version}.7z
          7z x tmp/VapourSynth64-Portable-${vs_version}.7z -obuild/Python3 -aos

          export PATH=$(pwd)/build/Python3:$(pwd)/build/Python3/Scripts:${PATH}
          VSPipe -v

      - name: Install VSRepo
        run: |
          export PATH=$(pwd)/build/Python3:$(pwd)/build/Python3/Scripts:${PATH}
          git clone https://github.com/vapoursynth/vsrepo tmp/vsrepo
          cd tmp/vsrepo
          python setup.py install
          cd ../../

      - name: Install Packages
        run: |
          export PATH=$(pwd)/build/Python3:$(pwd)/build/Python3/Scripts:${PATH}
          echo "Install Scripts.txt..."
          for pkg in $(cat config/Scripts.txt); do
            python -m vsrepo install ${pkg}
          done
          echo "Install Plugins.txt..."
          for pkg in $(cat config/Plugins.txt); do
            python -m vsrepo install ${pkg}
          done

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
        if: success() || failure()

      # - name: Zip
      #   shell: cmd
      #   run: |
      #     tar.exe -a -c -f Addons.zip --exclude "cython.py" --exclude ".keep" Python3.9/Lib/site-packages/*.py Python3.9/vapoursynth64/plugins/*

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: Addons.zip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
